### PR TITLE
Re-format project as a Go module

### LINKED ISSUE #303: build with go 1.13.3 fails with can't find import: "golang.org/x/text/transform"
dwayne@localhost:~/work$ git clone https://github.com/matrix-org/go-neb
Cloning into 'go-neb'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 7378 (delta 10), reused 27 (delta 8), pack-reused 7342
Receiving objects: 100% (7378/7378), 10.93 MiB | 19.56 MiB/s, done.
Resolving deltas: 100% (2683/2683), done.
dwayne@localhost:~/work$ cd go-neb
dwayne@localhost:~/work/go-neb$ gb build github.com/matrix-org/go-neb
# golang.org/x/text/runes
cond.go:10:2: can't find import: "golang.org/x/text/transform"
github.com/matrix-org/go-neb/api
github.com/Sirupsen/logrus
github.com/matrix-org/gomatrix
github.com/beorn7/perks/quantile
github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
github.com/prometheus/common/model
github.com/prometheus/procfs
github.com/mattn/go-shellwords
github.com/google/go-querystring/query
golang.org/x/net/context
github.com/matrix-org/go-neb/realms/jira/urls
github.com/die-net/lrucache
github.com/gregjones/httpcache
golang.org/x/net/html/atom
github.com/mmcdole/gofeed/extensions
github.com/mmcdole/goxpp
golang.org/x/text/encoding/internal/identifier
golang.org/x/text/internal/utf8internal
golang.org/x/text/internal/tag
github.com/shurcooL/sanitized_anchor_name
github.com/golang/protobuf/proto
gopkg.in/yaml.v2
# golang.org/x/text/encoding
encoding.go:20:2: can't find import: "golang.org/x/text/transform"
github.com/matrix-org/dugong
github.com/matrix-org/util
github.com/matrix-org/go-neb/types
github.com/andygrunwald/go-jira
golang.org/x/oauth2/internal
github.com/dghubble/oauth1
github.com/google/go-github/github
golang.org/x/text/language
golang.org/x/net/html
github.com/prometheus/client_model/go
github.com/matttproud/golang_protobuf_extensions/pbutil
github.com/russross/blackfriday
github.com/matrix-org/go-neb/services/echo
github.com/matrix-org/go-neb/database
github.com/matrix-org/go-neb/services/giphy
github.com/matrix-org/go-neb/services/google
github.com/matrix-org/go-neb/services/guggy
github.com/matrix-org/go-neb/services/imgur
golang.org/x/oauth2
github.com/matrix-org/go-neb/services/github/webhook
github.com/andybalholm/cascadia
github.com/jaytaylor/html2text
github.com/prometheus/common/expfmt
github.com/matrix-org/go-neb/services/slackapi
github.com/matrix-org/go-neb/matrix
github.com/matrix-org/go-neb/services/alertmanager
github.com/matrix-org/go-neb/services/travisci
github.com/matrix-org/go-neb/realms/jira
github.com/matrix-org/go-neb/services/github/client
github.com/PuerkitoBio/goquery
github.com/matrix-org/go-neb/services/wikipedia
github.com/prometheus/client_golang/prometheus
github.com/matrix-org/go-neb/services/jira/webhook
github.com/matrix-org/go-neb/realms/github
github.com/matrix-org/go-neb/metrics
github.com/matrix-org/go-neb/services/jira
github.com/matrix-org/go-neb/services/github
github.com/matrix-org/go-neb/clients
github.com/matrix-org/go-neb/polling
github.com/matrix-org/go-neb/api/handlers
github.com/mattn/go-sqlite3
FATAL: command "build" failed: exit status 2
dwayne@localhost:~/work/go-neb$ go version
go version go1.13.3 linux/amd64

### LINKED ISSUE #307: Support postgres
If purely so we can stop deploying db files everywhere.

### PR DESCRIPTION
**Pull request by nikofil**
* Re-format project to work with the latest versions of Go by using the [module format](https://github.com/golang/go/wiki/Modules). This way `gb` is no longer necessary as `go` can handle the vendoring. These changes are also reflected in the docs, dockerfile etc. (closes #303)

* Most of the dependencies were updated to their latest version. I fixed some cases where the API of some library changed and I needed to change a function call or package name.

* Add the postgres driver for working with psql. (closes #307)

I made this PR as I wanted to work with the latest version of Go. The tests work and I've tested the bot myself (also in Docker), so I don't think I've broken anything. Feedback welcome!

### CODE REVIEW

**Comment by ndom91** [comment]
@nikofil I wanted to try this out, but can't get it to build. What do I have to do to run this before it gets merged? 

`go build github.com/nikofil/go-neb` doesnt work and `go build . ` doesnt find any go files. 

Sorry I'm much more of a web guy than go so any help is appreciated ;)

**Comment by nikofil** [comment]
Sure, no problem! `go build .` should work, just make sure you checked out the right branch from my repository (`git clone https://github.com/nikofil/go-neb && cd go-neb && git checkout go-module && go build .`).

**Comment by ndom91** [comment]
> Sure, no problem! `go build .` should work, just make sure you checked out the right branch from my repository (`git clone https://github.com/nikofil/go-neb && cd go-neb && git checkout go-module && go build .`).

Didn't have the correct branch checked out :man_facepalming: haha all good now. Thanks!

**Comment by nikofil** [comment]
Sounds good! :) Let me know once the rest are merged and I can rebase this.

**Comment by Kegsay** [comment]
When #311 merges, this can be merged.

**Comment by ReK2Fernandez** [comment]
> When #311 merges, this can be merged.

have this happen already? Im waiting for this change to install, since I have all my go configs with go modules not a go ENV thanks

**Comment by Kegsay** [comment]
#311 has now landed so once this PR has been merged forward then this is ready to go.

**Comment by nikofil** [comment]
Rebased this - it should be ready to merge now.

**Pull request merged**
