### PR TITLE
400 if a service which needs a syncing client is configured without one

### PR DESCRIPTION
**Pull request by Kegsay**
This catches a common configuration error and fails early. Also, remove `roomID` from `Commands()` and `Expansions()` as we never used it.

### CODE REVIEW

**Comment by NegativeMjark** [comment]
Maybe s/syncing client/client with "Sync" enabled/ ?
LGTM.

**Comment by Kegsay** [comment]
I chose the wording carefully because I don't want the API for `/configureClient` to be leaking through to error messages in `/configureService`. I would like to `lower_case_and_underscores` all the APIs eventually, which would make the error message here misleading. The concept of a "syncing" client is a safer bet, and is unlikely to change however, hence why I chose that specific wording. WDYT?

**Comment by NegativeMjark** [comment]
Would it make sense for api.ClientConfig.Sync to use the phrase "syncing client" in its documentation?

**Comment by Kegsay** [comment]
Yes, good idea. Will do that instead.

**Pull request merged**
