### PR TITLE
alertmanager support

### PR DESCRIPTION
**Pull request by jcgruenhage**

### CODE REVIEW

**Comment by anoadragon453** [comment]
I just meant could it be a security risk ( not sure what data alert manager can produce and if it's sensitive).

**Comment by jcgruenhage** [comment]
I don't think it's sending any sensitive data, but that toally depends on how people configure it

**Comment by anoadragon453** [comment]
@jcgruenhage is it worth it to add a config option to disable it?

**Comment by jcgruenhage** [comment]
I don't think so. The bot has access to the messages it sends anyway, since it has a token of a user that is in that room. Also, I can't think of a threatmodel where you'd trust go-neb with the data but not it's logs.. Specifically, for people using it through scalar it will end up on matrix.org anyway, and for people who host it themselves they can just set the loglevel to get rid of it.

**Comment by Half-Shot** [comment]
I hope this was tested, btw?

**Comment by jcgruenhage** [comment]
Yes, it was

**Comment by MTRNord** [comment]
Just as I dont understand what this does :) What does this in case of Go-Neb? Is it Matrix->Prometheus or the other way around or did I missunderstood it completly?

**Comment by turt2live** [comment]
It's for alertmanager -> matrix

**Comment by MTRNord** [comment]
@turt2live ok thanks!

**Pull request merged**
