### PR TITLE
Bump Go version in Github CI

### PR DESCRIPTION
**Pull request by tadzik**

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
:shipit:

**Comment by tadzik** [comment]
I was hoping that the CI will actually check that it fixes things (it does seem to unblock `staticcheck` locally), but apparently its triggers don't include the workflow itself being changed. Is there any way I can force it to run here?

**Comment by t3chguy** [comment]
https://github.com/matrix-org/go-neb/runs/6008727796?check_suite_focus=true cherry-picked your commit over to https://github.com/matrix-org/go-neb/pull/358

**Comment by tadzik** [comment]
Ah, perfect. I guess we can close this one then, with that one going in.

**Comment by t3chguy** [comment]
sgtm, CI passed over in #358 with your change - thanks!

**Pull request closed without merging**
